// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LinqToSalesforce")>]
[<assembly: AssemblyProductAttribute("LinqToSalesforce")>]
[<assembly: AssemblyDescriptionAttribute("Linq provider for Salesforce SOQL REST API")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LinqToSalesforce"
    let [<Literal>] AssemblyProduct = "LinqToSalesforce"
    let [<Literal>] AssemblyDescription = "Linq provider for Salesforce SOQL REST API"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
