// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("LinqToSalesforce.VsPlugin2017")]
[assembly: AssemblyProductAttribute("LinqToSalesforce")]
[assembly: AssemblyDescriptionAttribute("Linq provider for Salesforce SOQL REST API")]
[assembly: AssemblyVersionAttribute("0.2.1")]
[assembly: AssemblyFileVersionAttribute("0.2.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "LinqToSalesforce.VsPlugin2017";
        internal const System.String AssemblyProduct = "LinqToSalesforce";
        internal const System.String AssemblyDescription = "Linq provider for Salesforce SOQL REST API";
        internal const System.String AssemblyVersion = "0.2.1";
        internal const System.String AssemblyFileVersion = "0.2.1";
    }
}
